### ISSUE TITLE
Multiple inputs error

### ISSUE THREAD

**Issue by mfinean** [sksq96/pytorch-summary#90]
When using multiple inputs i get the error "TypeError: can't multiply sequence by non-int of type 'tuple'" from np.prod

https://github.com/sksq96/pytorch-summary/blob/b50f213f38544ac337beeeda93b03c7e48e69c78/torchsummary/torchsummary.py#L100

Suggested fix - add the sum function:
np.prod(sum(input_size,()))

**Comment by apacha** [comment]
Wow! That is a great solution to the problem! Just had the same issue here.

```
import torch.nn.functional as F
from torch.nn import Module, Conv2d, MaxPool2d, Linear, AdaptiveAvgPool2d
from torchsummary import summary


class DetectionRefinementModel(Module):

    def __init__(self):
        super(DetectionRefinementModel, self).__init__()
        self.pool = MaxPool2d(2, 2)
        self.conv1 = Conv2d(3, 64, 3, padding=1)
        self.conv2 = Conv2d(64, 96, 3, padding=1)
        self.conv3 = Conv2d(96, 128, 3, padding=1)
        self.conv4 = Conv2d(128, 192, 3, padding=1)
        self.avg_pool = AdaptiveAvgPool2d((1, 1))
        self.linear1 = Linear(192, 64)
        self.linear2 = Linear(64, 4)

    def forward(self, image, unrefined_bounding_box):
        x = self.pool(F.relu(self.conv1(image)))
        x = self.pool(F.relu(self.conv2(x)))
        x = self.pool(F.relu(self.conv3(x)))
        x = F.relu(self.conv4(x))

        x = self.avg_pool(x)
        x = x.view(x.size(0), -1)
        x = F.relu(self.linear1(x))
        x = F.relu(self.linear2(x))
        x = x + unrefined_bounding_box

        return x


if __name__ == '__main__':
    network = DetectionRefinementModel()
    print(network)
    summary(network, [(3, 128, 1024), (4,)], device="cpu")
```

Your workaround fixed the problem here.

**Comment by Naireen** [comment]
Thank you @mfinean for the suggestion, the latest version of the code on master should now work!

**Comment by segalinc** [comment]
I have the latest version but I still have the problem and the code still look like the old version.

**Comment by shuboyang** [comment]
Amazing! That really works!
